#!/bin/bash

set -e

BASE="$(dirname "$0")"
SRC="$BASE/rootfs"
DST=/target
INPUT="${1:-input.qcow2}"
cd "$BASE"
. ./variables

guestfish -a "$INPUT" --rw << EOF
run
lcd "$SRC"
mount /dev/sda1 /
copy-in etc/apt /etc
copy-in etc/cloud /etc
copy-in etc/default /etc
copy-in etc/locale.gen /etc
copy-in etc/profile.d /etc
copy-in etc/skel /etc
copy-in etc/ssh /etc
copy-in etc/systemd /etc

# Simulate systemctl enable
ln-s /etc/systemd/system/vlab-startup.service /etc/systemd/system/multi-user.target.wants/vlab-startup.service
EOF
