#!/bin/bash

set -e

BASE="$(dirname "$0")"
SRC="$BASE/rootfs"
DST=/tmp/target
INPUT="${1:-input.qcow2}"
cd "$BASE"
. ./variables

qemu-img resize "$INPUT" 4096M
mkdir -p "$DST"
guestmount -a "$INPUT" -m /dev/sda1 "$DST"
trap 'fusermount -u "$DST"' EXIT

rsync -rlpt "$SRC"/etc/{apt,cloud,default,locale.gen,profile.d,skel,ssh,systemd} "$DST"/etc/

# Simulate systemctl enable
ln -sfn /etc/systemd/system/vlab-startup.service "$DST"/etc/systemd/system/multi-user.target.wants/vlab-startup.service
