---
- name: Configure Proxmox VE
  hosts: all
  vars:
    dpkg_diversions:
      - path: /etc/lvm/lvm.conf
        divert_to: /etc/lvm/lvm.conf.dpkg-divert

  tasks:
    - name: SSH access with CA
      ansible.builtin.copy:
        src: vlab_ca.pub
        dest: /etc/ssh/ssh_user_ca
        owner: root
        group: root
        mode: '0644'

    - name: Userns for LXC
      ansible.builtin.copy:
        dest: "{{ item }}"
        content: "root:100000:165536"
        owner: root
        group: root
        mode: '0644'
      loop:
        - /etc/subuid
        - /etc/subgid

    - name: Ensure known_hosts exists
      ansible.builtin.file:
        path: /etc/pve/priv/known_hosts
        state: touch
        force: true

    - name: Link ~/.ssh/known_hosts
      ansible.builtin.file:
        src: /etc/pve/priv/known_hosts
        dest: /root/.ssh/known_hosts
        state: link
        force: true

    - name: Chrony
      register: chrony_result
      ansible.builtin.copy:
        dest: /etc/chrony/sources.d/vlab.conf
        content: |
          # Vlab NTP servers
          server time.ustc.edu.cn iburst
        owner: root
        group: root
        mode: '0644'
      notify: Reload chrony

    - name: Sysctl
      ansible.builtin.copy:
        dest: /etc/sysctl.d/10-vlab.conf
        content: |
          # ARP
          net.ipv4.conf.all.arp_ignore = 1
          net.ipv4.conf.all.arp_announce = 2

          # inotify (for VSCode and various)
          fs.inotify.max_user_instances = 65536

          # keyctl (for Docker)
          kernel.keys.maxkeys = 50000
          kernel.keys.maxbytes = 1000000

          # conntrack
          net.nf_conntrack_max = 1048576

          # PIDs
          kernel.pid_max = 4194304

          # Miscellaneous networking
          net.core.default_qdisc = fq
          net.ipv4.tcp_congestion_control = bbr
          net.ipv4.ip_forward = 1
          net.ipv4.neigh.default.gc_thresh3 = 8192
          net.ipv6.neigh.default.gc_thresh3 = 8192
        owner: root
        group: root
        mode: '0644'

    - name: LXC config
      ansible.builtin.copy:
        dest: /usr/share/lxc/config/common.conf.d/10-vlab.conf
        content: |
          lxc.cgroup2.pids.max = 32768
          lxc.prlimit.memlock = 16777216

          # TUN device and KVM device
          lxc.cgroup2.devices.allow = c 10:200 rwm
          lxc.cgroup2.devices.allow = c 10:232 rwm

          # Limit tmpfs size
          lxc.mount.entry = tmpfs run tmpfs size=2G,mode=0755 0 0
          lxc.mount.entry = tmpfs dev/shm tmpfs size=4G,mode=1777,create=dir 0 0
        owner: root
        group: root
        mode: '0644'

    - name: SSHD config
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/vlab.conf
        content: |
          HostKey /etc/ssh/ssh_host_ed25519_key
          # RSA key is required for pvesh
          HostKey /etc/ssh/ssh_host_rsa_key
          HostCertificate /etc/ssh/ssh_host_ed25519_key-cert.pub
          TrustedUserCAKeys /etc/ssh/ssh_user_ca

          PermitRootLogin prohibit-password
          PasswordAuthentication no
          AuthorizedKeysFile none
        owner: root
        group: root
        mode: '0644'
      notify: Reload ssh.service

    - name: Check dpkg diversions
      ansible.builtin.command: dpkg-divert --list {{ item.path }}
      register: dpkg_divert_check
      failed_when: false
      changed_when: false
      loop: "{{ dpkg_diversions }}"
    - name: Add dpkg diversions if not present
      ansible.builtin.command: >
        dpkg-divert --add --rename
          --divert {{ item.item.divert_to }}
          {{ item.item.path }}
      when: item.stdout == ""
      loop: "{{ dpkg_divert_check.results }}"

    - name: Install lvm.conf
      ansible.builtin.copy:
        dest: /etc/lvm/lvm.conf
        content: |
          devices {
            # added by pve-manager to avoid scanning ZFS zvols
            global_filter=["r|/dev/zd.*|","r|/dev/rbd.*|"]
            scan_lvs=0
            issue_discards = 1
          }
          activation {
            auto_activation_volume_list = [ "pve", "data"{% if inventory_hostname == 'pv1' %}, "vlab-data"{% endif %} ]
          }
        owner: root
        group: root
        mode: '0644'

    - name: Save iptables
      ansible.builtin.copy:
        dest: "{{ item }}"
        content: |
          *nat
          :PREROUTING ACCEPT [0:0]
          :INPUT ACCEPT [0:0]
          :OUTPUT ACCEPT [0:0]
          :POSTROUTING ACCEPT [0:0]
          -A PREROUTING -m addrtype --dst-type LOCAL -p tcp --dport 443 -j REDIRECT --to-ports 8006
          COMMIT
        owner: root
        group: root
        mode: '0644'
      loop:
        - /etc/iptables/rules.v4
        - /etc/iptables/rules.v6

    - name: Fix iSCSI target quirks
      register: iscsi_udev_result
      ansible.builtin.copy:
        dest: /etc/udev/rules.d/99-scsi-zeroing-mode.rules
        content: |
          {%- if 'gen1' in group_names -%}
          ACTION=="add|change", SUBSYSTEM=="scsi_disk", DEVPATH=="/devices/platform/host*/session*/target*/*/scsi_disk/*", TEST=="zeroing_mode", ATTR{zeroing_mode}:="writesame"
          {%- elif 'gen2' in group_names -%}
          ACTION=="add|change", SUBSYSTEM=="scsi_disk", DEVPATH=="/devices/platform/host*/session*/target*/*/scsi_disk/*", TEST=="zeroing_mode", ATTR{zeroing_mode}:="write"
          ACTION=="add|change", SUBSYSTEM=="scsi_disk", DEVPATH=="/devices/platform/host*/session*/target*/*/scsi_disk/*", TEST=="max_write_same_blocks", ATTR{max_write_same_blocks}:="0"
          {%- endif %}
        owner: root
        group: root
        mode: '0644'
    - name: Call udev
      ansible.builtin.shell: |
        udevadm control --reload-rules
        udevadm trigger --subsystem-match=scsi_disk --action=change
      when: iscsi_udev_result.changed

    - name: Remove AF_ALG blacklist
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - /etc/modprobe.d/disable-algif.conf

    - name: Add dirtyfrag blacklist
      ansible.builtin.copy:
        dest: /etc/modprobe.d/dirtyfrag.conf
        content: |
          install esp4 /bin/false
          install esp6 /bin/false
          install ipcomp4 /bin/false
          install ipcomp6 /bin/false
          install rxrpc /bin/false
        owner: root
        group: root
        mode: '0644'

    - name: Unload dirtyfrag modules
      ansible.builtin.shell: |
        rmmod esp4 || true
        rmmod esp6 || true
        rmmod ipcomp4 || true
        rmmod ipcomp6 || true
        rmmod rxrpc || true

    - name: Add PinTheft blacklist
      ansible.builtin.copy:
        dest: /etc/modprobe.d/pintheft.conf
        content: |
          install rds /bin/false
          install rds_tcp /bin/false
        owner: root
        group: root
        mode: '0644'

    - name: Unload PinTheft modules
      ansible.builtin.shell: |
        rmmod rds_tcp || true
        rmmod rds || true

  handlers:
    - name: Reload ssh.service
      ansible.builtin.systemd:
        name: ssh.service
        state: reloaded

    - name: Reload chrony
      ansible.builtin.command: "chronyc reload sources"
      changed_when: false
