---
- name: Download pve-container on control node
  ansible.builtin.get_url:
    url: "https://github.com/USTC-vlab/pve-container/releases/download/6.1.13%2Bvlab1/pve-container_6.1.13+vlab1_all.deb"
    dest: "/tmp/pve-container.deb"
    mode: "0644"
    checksum: "sha256:eee6d6fe5aef604047f85c884222fe62cde78bf90b4c1e6bbb6090ef743058a5"
  delegate_to: localhost
  run_once: true

- name: Copy deb to remote
  ansible.builtin.copy:
    src: "/tmp/pve-container.deb"
    dest: "/tmp/pve-container.deb"
    mode: "0644"

- name: Unhold pve-container
  ansible.builtin.dpkg_selections:
    name: pve-container
    selection: install

- name: Install pve-container
  ansible.builtin.apt:
    deb: "/tmp/pve-container.deb"

- name: Hold pve-container
  ansible.builtin.dpkg_selections:
    name: pve-container
    selection: hold

- name: Remove old hack
  ansible.builtin.apt:
    name:
      - pve-lxc-btrfs
    state: absent

- name: Cleanup
  ansible.builtin.file:
    path: "/tmp/pve-container.deb"
    state: absent
