---
- name: Download pve-container on control node
  ansible.builtin.get_url:
    url: "https://github.com/USTC-vlab/pve-container/releases/download/6.1.11%2Bvlab2/pve-container_6.1.11+vlab2_all.deb"
    dest: "/tmp/pve-container.deb"
    mode: "0644"
    checksum: "sha256:7d6ca90e8aff188fd0c06d8132665d82d2b004b74c68e368d776743a57d4d4a1"
  delegate_to: localhost
  run_once: true

- name: Copy deb to remote
  ansible.builtin.copy:
    src: "/tmp/pve-container.deb"
    dest: "/tmp/pve-container.deb"
    mode: "0644"

- name: Install pve-container
  ansible.builtin.apt:
    deb: "/tmp/pve-container.deb"

- name: Hold pve-container
  ansible.builtin.dpkg_selections:
    name: pve-container
    selection: hold

- name: Remove old hack
  ansible.builtin.apt:
    name:
      - pve-lxc-btrfs
    state: absent

- name: Cleanup
  ansible.builtin.file:
    path: "/tmp/pve-container.deb"
    state: absent
